# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    container_name: ignitecall_db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker